# This file generates the GitHub Actions matrix
# For simple board + shield combinations, add them
# to the top level board and shield arrays, for more
# control, add individual board + shield combinations to
# the `include` property, e.g:
#
# board: [ "nice_nano_v2" ]
# shield: [ "corne_left", "corne_right" ]
# include:
#   - board: bdn9_rev2
#   - board: nice_nano_v2
#     shield: reviung41
#
---
include:
  # dongle
  - board: nice_nano_v2
    shield: mriya_central_dongle
    artifact-name: mriya_dongle_nice_nano_v2
    # central_left
  - board: nice_nano_v2
    shield: mriya_central_left nice_view_adapter nice_view_gem
    artifact-name: mriya_central_left
  # peripheral
  - board: nice_nano_v2
    shield: mriya_peripheral_left nice_view_adapter nice_view_gem
    artifact-name: mriya_peripheral_left
  - board: nice_nano_v2
    shield: mriya_peripheral_right nice_view_adapter nice_view_gem
    artifact-name: mriya_peripheral_right
  # reset
  - board: nice_nano_v2
    shield: settings_reset
    artifact-name: settings_reset_nice_nano_v2
